### ISSUE TITLE
Bring sycl backends in line with the Cpp Core Guidelines

### ISSUE THREAD

**Issue by kris-rowe** [argonne-lcf/libCEED#13]
## Details

- http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html

## Todo 

*This list is not comprehensive*

- [ ] Use unnamed namespace instead of `static for local helper functions ([F22](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf22-use-an-unnamed-anonymous-namespace-for-all-internalnon-exported-entities))
- [ ] Eliminate output parameters by returning in a tuple with the error flag ([F21](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-out-multi))
- [ ] Add `not_null` where appropriate ([F23](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-nullptr))
