### ISSUE TITLE
Convert basic `parallel_for` kernel launches to `nd_range`

### ISSUE THREAD

**Issue by kris-rowe** [argonne-lcf/libCEED#46]
## Details

The work group size chosen by the SYCL runtime for the basic  `parallel_for` kernel launches is suboptimal in some cases. These should be converted to the `nd_range` version and an appropriate default work group size should be found in each case.

_Note: basic `parallel_for` usage is limited to the sycl-ref backend_.

## Todo

- [ ] Get baseline performance data for relevant kernels
- [ ] Evaluate performance using `nd_range` kernel launch

### Vector

- [ ] Norm (x3)
- [ ] Reciprocal
- [ ] Scale
- [ ] AXPY
- [ ] PointwiseMult

### ElementRestriction

- [ ] [StridedNoTranspose](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-restriction.sycl.cpp#L39)
- [ ] [OffsetNoTranspose](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-restriction.sycl.cpp#L66)
- [ ] [StridedTranspose](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-restriction.sycl.cpp#L94)
- [ ] [OffsetTranspose](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-restriction.sycl.cpp#L124)

### Basis

- [ ] [ApplyWeight](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-ref-basis.sycl.cpp#L220)
- [ ] [ApplyNonTensorInterp](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-ref-basis.sycl.cpp#L311)
- [ ] [ApplyNonTensorGrad](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-ref-basis.sycl.cpp#L355)
- [ ] [ApplyNonTensorWeight](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-ref-basis.sycl.cpp#L393)

### QFunction

- [ ] [Apply](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-ref-qfunction.sycl.cpp#L79)

### Operator

- [ ] [LinearDiagonal](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-ref-operator.sycl.cpp#L856)
- [ ] [Linear Assemble](https://github.com/argonne-lcf/libCEED/blob/5c04eaa1d20ca27452424062a32acc3175dd13a5/backends/sycl-ref/ceed-sycl-ref-operator.sycl.cpp#L1215)
